# Generated by Django 6.0.2 on 2026-02-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_branch_alter_user_managers_alter_user_email_auditlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('BRANCH_CREATED', 'Branch Created'), ('BRANCH_UPDATED', 'Branch Updated'), ('BRANCH_TOGGLED', 'Branch Toggled'), ('USER_INVITED', 'User Invited'), ('USER_UPDATED', 'User Updated'), ('USER_ACTIVATED', 'User Activated'), ('USER_DEACTIVATED', 'User Deactivated'), ('USER_ROLE_CHANGED', 'User Role Changed'), ('USER_BRANCH_CHANGED', 'User Branch Changed'), ('PASSWORD_SET_VIA_INVITE', 'Password Set Via Invite'), ('CLIENT_CREATED', 'Client Created'), ('CLIENT_STATUS_CHANGED', 'Client Status Changed')], max_length=50),
        ),
    ]
