# Generated by Django 6.0.2 on 2026-02-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('BRANCH_CREATED', 'Branch Created'), ('BRANCH_UPDATED', 'Branch Updated'), ('BRANCH_TOGGLED', 'Branch Toggled'), ('USER_INVITED', 'User Invited'), ('USER_UPDATED', 'User Updated'), ('USER_ACTIVATED', 'User Activated'), ('USER_DEACTIVATED', 'User Deactivated'), ('USER_ROLE_CHANGED', 'User Role Changed'), ('USER_BRANCH_CHANGED', 'User Branch Changed'), ('PASSWORD_SET_VIA_INVITE', 'Password Set Via Invite'), ('CLIENT_CREATED', 'Client Created'), ('CLIENT_STATUS_CHANGED', 'Client Status Changed'), ('KYC_INITIATED', 'KYC Initiated'), ('KYC_DOCUMENT_UPLOADED', 'KYC Document Uploaded'), ('KYC_APPROVED', 'KYC Approved'), ('KYC_REJECTED', 'KYC Rejected'), ('CLIENT_DEACTIVATED', 'Client Deactivated')], max_length=50),
        ),
    ]
