# Generated by Django 6.0.2 on 2026-02-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('BRANCH_CREATED', 'Branch Created'), ('BRANCH_UPDATED', 'Branch Updated'), ('BRANCH_TOGGLED', 'Branch Toggled'), ('USER_INVITED', 'User Invited'), ('USER_UPDATED', 'User Updated'), ('USER_ACTIVATED', 'User Activated'), ('USER_DEACTIVATED', 'User Deactivated'), ('USER_ROLE_CHANGED', 'User Role Changed'), ('USER_BRANCH_CHANGED', 'User Branch Changed'), ('PASSWORD_SET_VIA_INVITE', 'Password Set Via Invite'), ('CLIENT_CREATED', 'Client Created'), ('CLIENT_STATUS_CHANGED', 'Client Status Changed'), ('KYC_INITIATED', 'KYC Initiated'), ('KYC_DOCUMENT_UPLOADED', 'KYC Document Uploaded'), ('KYC_APPROVED', 'KYC Approved'), ('KYC_REJECTED', 'KYC Rejected'), ('CLIENT_DEACTIVATED', 'Client Deactivated'), ('LOAN_CREATED', 'Loan Created'), ('REPAYMENT_RECORDED', 'Repayment Recorded'), ('LOAN_CLOSED', 'Loan Closed'), ('SAVINGS_ACCOUNT_CREATED', 'Savings Account Created'), ('SAVINGS_DEPOSIT_POSTED', 'Savings Deposit Posted'), ('SAVINGS_WITHDRAWAL_POSTED', 'Savings Withdrawal Posted'), ('SAVINGS_WITHDRAWAL_REQUESTED', 'Savings Withdrawal Requested'), ('SAVINGS_WITHDRAWAL_APPROVED', 'Savings Withdrawal Approved'), ('SAVINGS_WITHDRAWAL_REJECTED', 'Savings Withdrawal Rejected'), ('SAVINGS_ACCOUNT_FROZEN', 'Savings Account Frozen'), ('SAVINGS_ACCOUNT_CLOSED', 'Savings Account Closed')], max_length=50),
        ),
    ]
