# Generated by Django 6.0.2 on 2026-02-28 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_auditlog_action'),
        ('accounts', '0006_user_failed_login_attempts_alter_auditlog_action'),
    ]

    operations = [
    ]
