# Generated by Django 6.0.2 on 2026-02-28 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # the second dependency referenced a migration that was removed
        # accidentally; we only need to depend on the real 0006 file here.
        ('accounts', '0006_alter_auditlog_action'),
    ]

    operations = [
    ]
