# Generated by Django 6.0.2 on 2026-02-28 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_20260228_0948'),
        ('accounts', '0007_merge_20260228_0951'),
    ]

    operations = [
    ]
