# Generated by Django 6.0.2 on 2026-02-09 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_kyc_status_clientkyc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='kyc_status',
        ),
        migrations.DeleteModel(
            name='ClientKYC',
        ),
    ]
