# Generated by Django 6.0.2 on 2026-02-10 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_status_kyc_kycdocument'),
        ('clients', '0003_remove_client_kyc_status_delete_clientkyc'),
    ]

    operations = [
    ]
