# Generated by Django 6.0.2 on 2026-02-11 13:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_merge_20260210_0849'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='kycdocument',
            constraint=models.UniqueConstraint(fields=('kyc', 'document_type'), name='unique_kyc_document_type'),
        ),
    ]
