# Generated by Django 6.0.2 on 2026-02-28 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='savingsaccount',
            new_name='savings_sav_branch__d639fa_idx',
            old_name='savings_sav_branch__aa9d5f_idx',
        ),
        migrations.RenameIndex(
            model_name='savingsaccount',
            new_name='savings_sav_client__50404a_idx',
            old_name='savings_sav_client__9bf1cf_idx',
        ),
        migrations.RenameIndex(
            model_name='savingstransaction',
            new_name='savings_sav_account_7961aa_idx',
            old_name='savings_sav_account__90db84_idx',
        ),
        migrations.RenameIndex(
            model_name='savingstransaction',
            new_name='savings_sav_account_3c1034_idx',
            old_name='savings_sav_account__aa711b_idx',
        ),
    ]
