# Generated by Django 6.0.2 on 2026-02-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_rename_savings_sav_branch__aa9d5f_idx_savings_sav_branch__d639fa_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingstransaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money'), ('CHECK', 'Check')], max_length=32, null=True),
        ),
    ]
