# Generated by Django 6.0.2 on 2026-02-11 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='loan',
            new_name='loans_loan_client__a27993_idx',
            old_name='loans_loan_client__a4c8ee_idx',
        ),
        migrations.RenameIndex(
            model_name='loaninstallment',
            new_name='loans_loani_loan_id_3c2c95_idx',
            old_name='loans_loanin_loan_id_2c1dc1_idx',
        ),
        migrations.RenameIndex(
            model_name='loaninstallment',
            new_name='loans_loani_loan_id_70533c_idx',
            old_name='loans_loanin_loan_id_686451_idx',
        ),
        migrations.RenameIndex(
            model_name='repayment',
            new_name='loans_repay_loan_id_dd8692_idx',
            old_name='loans_repay_loan_id_9c3f2f_idx',
        ),
    ]
