# Generated by Django 6.0.2 on 2026-02-11 13:40
# Fixed to use conditional RunSQL for index renames (handle cases where index may not exist)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        # Conditionally rename loans_loan_client__a4c8ee_idx → loans_loan_client__a27993_idx
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'loans_loan_client__a4c8ee_idx') THEN
                    ALTER INDEX loans_loan_client__a4c8ee_idx RENAME TO loans_loan_client__a27993_idx;
                END IF;
            END $$;
            """,
            reverse_sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'loans_loan_client__a27993_idx') THEN
                    ALTER INDEX loans_loan_client__a27993_idx RENAME TO loans_loan_client__a4c8ee_idx;
                END IF;
            END $$;
            """,
        ),
        # Conditionally rename loans_loanin_loan_id_2c1dc1_idx → loans_loani_loan_id_3c2c95_idx
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'loans_loanin_loan_id_2c1dc1_idx') THEN
                    ALTER INDEX loans_loanin_loan_id_2c1dc1_idx RENAME TO loans_loani_loan_id_3c2c95_idx;
                END IF;
            END $$;
            """,
            reverse_sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'loans_loani_loan_id_3c2c95_idx') THEN
                    ALTER INDEX loans_loani_loan_id_3c2c95_idx RENAME TO loans_loanin_loan_id_2c1dc1_idx;
                END IF;
            END $$;
            """,
        ),
        # Conditionally rename loans_loanin_loan_id_686451_idx → loans_loani_loan_id_70533c_idx
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'loans_loanin_loan_id_686451_idx') THEN
                    ALTER INDEX loans_loanin_loan_id_686451_idx RENAME TO loans_loani_loan_id_70533c_idx;
                END IF;
            END $$;            python manage.py migrate loans 0002 --fake
            python manage.py migrate
            """,
            reverse_sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'loans_loani_loan_id_70533c_idx') THEN
                    ALTER INDEX loans_loani_loan_id_70533c_idx RENAME TO loans_loanin_loan_id_686451_idx;
                END IF;
            END $$;
            """,
        ),
        # Conditionally rename loans_repay_loan_id_9c3f2f_idx → loans_repay_loan_id_dd8692_idx
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'loans_repay_loan_id_9c3f2f_idx') THEN
                    ALTER INDEX loans_repay_loan_id_9c3f2f_idx RENAME TO loans_repay_loan_id_dd8692_idx;
                END IF;
            END $$;
            """,
            reverse_sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'loans_repay_loan_id_dd8692_idx') THEN
                    ALTER INDEX loans_repay_loan_id_dd8692_idx RENAME TO loans_repay_loan_id_9c3f2f_idx;
                END IF;
            END $$;
            """,
        ),
    ]
