# Generated by Django 6.0.2 on 2026-02-18 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_loan_add_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loans.loanproduct'),
        ),
    ]
