# Generated by Django 6.0.2 on 2026-02-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0017_declare_existing_fields_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for loan rejection'),
        ),
    ]
