# Generated by Django 6.0.2 on 2026-02-20 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_rename_loans_loan_client__a4c8ee_idx_loans_loan_client__a27993_idx_and_more'),
        ('loans', '0023_reset_loanproductrequireddocument_schema'),
    ]

    operations = [
    ]
