# Generated by Django 6.0.2 on 2026-02-23 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0027_loandocument_unique_constraint'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='loandocument',
            name='loans_loand_loan_id_uploads_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='loandocument',
            name='loans_loand_loan_id_doc_type_idx',
        ),
    ]
