# Generated by Django 6.0.2 on 2026-02-28 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001__initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cashledgerentry',
            new_name='cash_cashle_branch__d026fd_idx',
            old_name='cash_ledger_branch_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='cashledgerentry',
            new_name='cash_cashle_session_7b99a9_idx',
            old_name='cash_ledger_session_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='cashledgerentry',
            new_name='cash_cashle_referen_d686c9_idx',
            old_name='cash_ledger_reference_idx',
        ),
        migrations.RenameIndex(
            model_name='tellersession',
            new_name='cash_teller_branch__4809b7_idx',
            old_name='cash_teller_branch_cashier_status_idx',
        ),
        migrations.RenameIndex(
            model_name='tellersession',
            new_name='cash_teller_branch__439286_idx',
            old_name='cash_teller_branch_status_idx',
        ),
    ]
